"""Migration drift: the ORM models and the alembic head must describe the same schema.

`alembic check` (autogenerate diff against a database migrated to head) fails when a
model change ships without a migration, or when a models module is not imported by
alembic/env.py. Needs Postgres (TEST_DATABASE_URL); the schema is dropped and recreated.
"""

from __future__ import annotations

import asyncio
import os

import pytest

pytestmark = pytest.mark.integration


async def _reset_schema(url: str) -> None:
    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    from posture.config import Settings

    eng = create_async_engine(Settings(database_url=url).database_url)
    async with eng.begin() as conn:
        await conn.execute(text("DROP SCHEMA public CASCADE"))
        await conn.execute(text("CREATE SCHEMA public"))
    await eng.dispose()


def _config(url: str):
    from pathlib import Path

    from alembic.config import Config

    import posture
    from posture.config import Settings

    cfg = Config()
    cfg.set_main_option("script_location", str(Path(posture.__file__).parent / "alembic"))
    cfg.set_main_option("sqlalchemy.url", Settings(database_url=url).database_url.replace("%", "%%"))
    return cfg


async def test_alembic_check_no_drift():
    from alembic import command

    url = os.environ["TEST_DATABASE_URL"]
    await _reset_schema(url)
    cfg = _config(url)
    await asyncio.to_thread(command.upgrade, cfg, "head")
    # raises alembic.util.exc.AutogenerateDiffsDetected listing the drift
    await asyncio.to_thread(command.check, cfg)


def test_env_imports_every_models_module():
    """Static guard that also runs without Postgres."""
    from pathlib import Path

    import posture

    root = Path(posture.__file__).parent
    env = (root / "alembic" / "env.py").read_text()
    for mod in sorted(root.rglob("models.py")):
        dotted = "posture." + ".".join(mod.relative_to(root).with_suffix("").parts)
        if "__tablename__" not in mod.read_text():
            continue
        assert f"import {dotted}" in env or f"from {dotted} import" in env, f"alembic/env.py must import {dotted}"
