"""Compliance reports (DESIGN §11): `/reports*` and `GET /compliance/stig`."""

from __future__ import annotations

import asyncio
import uuid
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from .. import report_jobs
from ..auth import User, require_admin
from ..db.models import ConsensusFindingRow, ContainerRow, Image, PostureResultRow, Report, Scan, WorkloadRow
from ..db.models import ScannerStatus as ScannerStatusRow
from ..db.session import get_session
from ..logs import get_logger
from ..reports import registry
from ..reports.registry import ReportDependencyMissing, UnsupportedReport
from ..reports.stig import stig_rollup
from ..views import SCANNERS, latest_done_scan

log = get_logger(__name__)
router = APIRouter(tags=["reports"])


class ScopeIn(BaseModel):
    kind: str = "cluster"
    name: str | None = Field(default=None, max_length=512)


class ReportRequest(BaseModel):
    type: str = Field(max_length=32)
    format: str | None = Field(default=None, max_length=16)
    scope: ScopeIn | None = None
    scanId: int | None = None  # noqa: N815
    options: dict[str, Any] | None = None


def _pdf_available() -> None:
    """Fail fast (503) when WeasyPrint's system libraries are missing."""
    try:
        import weasyprint  # noqa: F401
    except (ImportError, OSError) as exc:
        raise ReportDependencyMissing(f"PDF rendering unavailable: {str(exc).splitlines()[0]}") from exc


def _uuid(report_id: str) -> uuid.UUID:
    try:
        return uuid.UUID(report_id)
    except ValueError:
        raise HTTPException(404, detail="report not found") from None


def _report_path(row: Report) -> Path | None:
    """The report file, only if it lies inside REPORTS_DIR (a tampered `reports.path` must not
    turn download/delete into arbitrary file read/unlink). None when it does not."""
    base = report_jobs.reports_dir().resolve()
    candidate = Path(row.path) if row.path else base / f"{row.id}.{row.format}"
    try:
        resolved = candidate.resolve()
    except (OSError, RuntimeError):
        return None
    if resolved.parent != base and base not in resolved.parents:
        log.warning("report.path_outside_reports_dir", report_id=str(row.id), path=str(candidate)[:300])
        return None
    return resolved


@router.get("/reports/types")
async def report_types() -> list[dict[str, Any]]:
    return [{**t, "defaultFormat": report_jobs.DEFAULT_FORMATS.get(t["type"], t["formats"][0])}
            for t in registry.REPORT_TYPES]


@router.get("/reports")
async def list_reports(scanId: int | None = None, type: str | None = None,  # noqa: A002,N803
                       session: AsyncSession = Depends(get_session)) -> list[dict[str, Any]]:
    stmt = select(Report)
    if scanId is not None:
        stmt = stmt.where(Report.scan_id == scanId)
    if type:
        stmt = stmt.where(Report.type.in_(type.split(",")))
    rows = (await session.execute(stmt.order_by(Report.created_at.desc()).limit(500))).scalars().all()
    return [report_jobs.report_dict(r) for r in rows]


@router.post("/reports", status_code=202)
async def create_report(body: ReportRequest, user: User = Depends(require_admin),
                        session: AsyncSession = Depends(get_session)) -> dict[str, Any]:
    scope = body.scope.model_dump() if body.scope else None
    try:
        fmt, kind, name = report_jobs.validate_request(body.type, body.format, scope, body.options)
        if fmt == "pdf":
            _pdf_available()
    except UnsupportedReport as e:
        raise HTTPException(422, detail=str(e)) from e
    except ReportDependencyMissing as e:
        raise HTTPException(503, detail=str(e)) from e
    async with session.begin():
        if body.scanId is not None:
            scan = await session.get(Scan, body.scanId)
            if scan is None:
                raise HTTPException(404, detail="scan not found")
            if scan.status != "done":
                raise HTTPException(409, detail=f"scan {scan.id} is {scan.status}, not done")
        else:
            scan = await latest_done_scan(session)
            if scan is None:
                raise HTTPException(409, detail="no completed scan yet")
        row = await report_jobs.create_row(session, report_type=body.type, fmt=fmt, scope_kind=kind,
                                           scope_name=name, scan_id=scan.id, options=body.options,
                                           created_by=user.username)
        out = report_jobs.report_dict(row)
    # generated by the report worker (posture.report_worker), never in the API process
    log.info("report.requested", report_id=out["id"], type=body.type, format=fmt, scope=kind, user=user.username)
    return out


@router.get("/reports/{report_id}")
async def get_report(report_id: str, session: AsyncSession = Depends(get_session)) -> dict[str, Any]:
    row = await session.get(Report, _uuid(report_id))
    if row is None:
        raise HTTPException(404, detail="report not found")
    return report_jobs.report_dict(row)


@router.get("/reports/{report_id}/download")
async def download_report(report_id: str, session: AsyncSession = Depends(get_session)):
    row = await session.get(Report, _uuid(report_id))
    if row is None:
        raise HTTPException(404, detail="report not found")
    if row.status != "done" or not row.path:
        raise HTTPException(409, detail=f"report is {row.status}")
    path = _report_path(row)
    if path is None or not await asyncio.to_thread(path.is_file):
        raise HTTPException(410, detail="report file is missing (storage was reset); generate it again")
    return FileResponse(path, media_type=row.content_type or "application/octet-stream",
                        filename=row.filename or path.name, content_disposition_type="attachment",
                        headers={"Cache-Control": "no-store", "X-Content-Type-Options": "nosniff"})


@router.delete("/reports/{report_id}", status_code=204)
async def delete_report(report_id: str, user: User = Depends(require_admin),
                        session: AsyncSession = Depends(get_session)) -> Response:
    rid = _uuid(report_id)
    async with session.begin():
        row = await session.get(Report, rid, with_for_update=True)
        if row is None:
            raise HTTPException(404, detail="report not found")
        path = _report_path(row)
        meta = {"type": row.type, "format": row.format, "scan_id": row.scan_id, "created_by": row.created_by}
        await session.delete(row)
    if path is not None:
        await asyncio.to_thread(report_jobs.delete_file, str(path))
    # security review L7: deletions of ATO evidence are attributed
    log.info("report.deleted", report_id=str(rid), user=user.username, **meta)
    return Response(status_code=204)


async def stig_snapshot(session: AsyncSession, scan: Scan) -> dict[str, Any]:
    """Just what the STIG rule evaluation reads (posture results, workloads, fixable findings,
    scanner status), straight from the tables: no full report snapshot (architecture review §4)."""
    from .. import app_settings

    settings = await app_settings.load(session)
    posture = [{"check_id": r.check_id, "status": r.status, "namespace": r.namespace, "kind": r.kind,
                "name": r.name, "container": r.container or None, "detail": r.detail or "", "severity": r.severity,
                "system_namespace": r.system_namespace}
               for r in (await session.execute(select(PostureResultRow).where(PostureResultRow.scan_id == scan.id)
                                               )).scalars()]
    workloads = [{"namespace": w.namespace, "kind": w.kind, "name": w.name, "pack": w.pack,
                  "image_ids": list(w.image_ids or []), "system_namespace": w.system_namespace}
                 for w in (await session.execute(select(WorkloadRow).where(WorkloadRow.scan_id == scan.id))).scalars()]
    img_ids = select(ContainerRow.image_fk).where(ContainerRow.scan_id == scan.id,
                                                  ContainerRow.image_fk.isnot(None)).distinct()
    c = ConsensusFindingRow
    findings = [{"image_id": f.image_id, "vuln_id": f.vuln_id, "severity": f.severity, "package": f.package,
                 "fixed_version": f.fixed_version or "", "fixable": True, "first_seen_at": f.first_seen_at}
                for f in (await session.execute(
                    select(c.image_id, c.vuln_id, c.severity, c.package, c.fixed_version, c.first_seen_at)
                    .where(c.image_id.in_(img_ids), c.fixable.is_(True),
                           c.severity.in_(("critical", "high", "medium", "low")))
                )).all()]
    hit = {f["image_id"] for f in findings}
    images = [{"id": i.id, "ref": i.ref, "digest": i.digest or ""} for i in (await session.execute(
        select(Image.id, Image.ref, Image.digest).where(Image.id.in_(hit or {0})))).all()]
    enabled = settings.scanners.model_dump()
    srows = {r.name: r for r in (await session.execute(select(ScannerStatusRow))).scalars()}
    scanners = [{"name": n, "enabled": enabled[n], "version": (srows[n].version or "") if n in srows else "",
                 "healthy": bool(srows[n].healthy) if n in srows else False} for n in SCANNERS]
    return {"generated_at": None, "scan": {"id": scan.id, "status": scan.status, "started_at": scan.started_at,
                                           "finished_at": scan.finished_at},
            "scanners": scanners, "images": images, "findings": findings, "workloads": workloads,
            "posture_results": posture}


@router.get("/compliance/stig")
async def compliance_stig(session: AsyncSession = Depends(get_session)) -> dict[str, Any]:
    """`items`: Kubernetes STIG rule rollup (DESIGN §11; the UI also accepts the bare list this
    used to be). `product`: OS / product STIGs inside images per benchmark (DESIGN §14)."""
    from .stig import benchmark_rollup, stig_summary
    from ..views import current_image_ids

    latest = await latest_done_scan(session)
    rules: list[dict[str, Any]] = []
    if latest is not None:
        snapshot = await stig_snapshot(session, latest)
        rules = await asyncio.to_thread(stig_rollup, snapshot, None)
        for r in rules:
            r["checkId"] = (r.get("checks") or [None])[0]
    product = {"benchmarks": await benchmark_rollup(session),
               **await stig_summary(session, await current_image_ids(session, latest))}
    return {"items": rules, "product": product}
